In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
import pandas as pd
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report,confusion_matrix

### Training labelled sentiment data

First let's load the sentiment data. In part 1 of this series we prepared the sentiment data so that it is divided in the input and output (target) variables. Let's load the prepared data.

In [2]:
target = np.load('target.npy')/4
sent_input = np.load('sentiment_input.npy')

print(sent_input.shape)
print(target.shape)

(1600000, 100)
(1600000, 1)


In [3]:
# Splitting input and output variables into training and test sets
X = sent_input
y = target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=7)

In [4]:
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)

/Users/dennis/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LinearDiscriminantAnalysis()

### Model Overview

In [5]:
y_pred = lda.predict(X_test)
print(y_pred)

[0. 0. 1. ... 1. 1. 1.]


In [6]:
def get_metrics(y_test, y_predicted):  
    # true positives / (true positives+false positives)
    precision = precision_score(y_test, y_predicted, pos_label=None,
                                    average='weighted')             
    # true positives / (true positives + false negatives)
    recall = recall_score(y_test, y_predicted, pos_label=None,
                              average='weighted')
    
    # harmonic mean of precision and recall
    f1 = f1_score(y_test, y_predicted, pos_label=None, average='weighted')
    
    # true positives + true negatives/ total
    accuracy = accuracy_score(y_test, y_predicted)
    return accuracy, precision, recall, f1

In [7]:
accuracy, precision, recall, f1 = get_metrics(y_test, y_pred)
print("accuracy = %.3f, precision = %.3f, recall = %.3f, f1 = %.3f" % (accuracy, precision, recall, f1))

accuracy = 0.694, precision = 0.694, recall = 0.694, f1 = 0.694


In [8]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.70      0.68      0.69    201003
         1.0       0.69      0.71      0.70    198997

    accuracy                           0.69    400000
   macro avg       0.69      0.69      0.69    400000
weighted avg       0.69      0.69      0.69    400000



In [9]:
print(confusion_matrix(y_test,y_pred))

[[137296  63707]
 [ 58605 140392]]


In [10]:
error_lda = pd.DataFrame({
        'Actual Values': np.array(y_test).flatten(),
        'Predicted Values': y_pred.flatten()})
error_lda

Actual Values  Predicted Values
0                 0.0               0.0
1                 0.0               0.0
2                 0.0               1.0
3                 0.0               0.0
4                 1.0               1.0
...               ...               ...
399995            0.0               1.0
399996            0.0               0.0
399997            0.0               1.0
399998            0.0               1.0
399999            1.0               1.0

[400000 rows x 2 columns]

In [11]:
# the probability of each sample belonging to each of the two classes
y_pred_proba = lda.predict_proba(X_test)

In [12]:
print(y_pred_proba)
print(y_pred_proba)

[[0.76496166 0.23503834]
 [0.63058882 0.36941118]
 [0.22380843 0.77619157]
 ...
 [0.32994998 0.67005002]
 [0.38721803 0.61278197]
 [0.34716863 0.65283137]]
[[0.76496166 0.23503834]
 [0.63058882 0.36941118]
 [0.22380843 0.77619157]
 ...
 [0.32994998 0.67005002]
 [0.38721803 0.61278197]
 [0.34716863 0.65283137]]


### Predicting the sentiment of covid tweets

In [13]:
covid_data = np.load('vectorized_100.npy')

In [14]:
print(covid_data.shape)

(8981, 100)


In [15]:
covid_predictions = lda.predict(covid_data)

In [16]:
covid_predicted_values = pd.DataFrame({
        'Predicted Values': covid_predictions.flatten()})

covid_predicted_values

Predicted Values
0                  0.0
1                  0.0
2                  0.0
3                  0.0
4                  0.0
...                ...
8976               0.0
8977               0.0
8978               0.0
8979               0.0
8980               1.0

[8981 rows x 1 columns]

In [17]:
covid_predicted_values.shape

(8981, 1)

In [18]:
# the probability of each sample belonging to each of the two classes
covid_predictions_probability = lda.predict_proba(covid_data)

In [19]:
covid_negative_probability=[]
covid_positive_probability=[]
for i in covid_predictions_probability:
    covid_positive_probability.append(i[1])
    covid_negative_probability.append(i[0])

In [20]:
print(len(covid_positive_probability))
print(len(covid_negative_probability))

8981
8981


In [21]:
data_country_random = pd.read_csv('data_country_random.csv')

In [22]:
data_country_random['predictions'] = covid_predicted_values
data_country_random['positive_probability'] = covid_positive_probability
data_country_random['negative_probability'] = covid_negative_probability

In [23]:
data_country_random.head()

Unnamed: 0        user_name               user_location  \
0           0            UNCDF                New York, NY   
1           1  Zachary Burkett                  Austin, TX   
2           2      Reshma Jose            Chalakudy, India   
3           3        @Caerdael                      Genève   
4           4    Douglas Clark  University of Saskatchewan   

                                    user_description         user_created  \
0  Making Finance Work for the Poor: #LDCs, #Fina...  2013-05-15 15:37:50   
1  I have NO FAITH in the Trump Administration. I...  2013-11-09 21:20:12   
2                          Bold and beautiful......!  2019-03-21 04:22:32   
3  Artiste peintre \n \n@IFJGlobal @ICIJorg @amne...  2010-03-15 16:16:41   
4  Associate Professor at @usaskSENS. Tweets on h...  2012-10-05 15:56:52   

   user_followers  user_friends  user_favourites  user_verified  \
0           14838           936            404.0            NaN   
1              35            87            409.0            NaN   
2              44           191              7.0            NaN   
3             278           190          16673.0            NaN   
4             993           832          16845.0            NaN   

                  date  ...  \
0  2020-08-11 08:34:02  ...   
1  2020-08-14 04:12:05  ...   
2  2020-08-17 06:40:59  ...   
3  2020-08-16 09:25:31  ...   
4  2020-07-28 03:02:35  ...   

                                        cleaned_text  \
0  humans unlimited needs planet limited capacity...   
1  realdonaldtrump never run away covid19 nov 202...   
2  simply sitting never means nothing morningmoti...   
3  millions covid19 funds flow el salvador imfnew...   
4  probably wouldnt possible design pathogen coul...   

                          cleaned_tags  len_hashtag language        country  \
0                        sdgs, covid19          2.0       en  United States   
1                              covid19          1.0       en  United States   
2  morningmotivation, covid19, chingam          3.0       en          India   
3                              covid19          1.0       en    Switzerland   
4                              covid19          1.0       en         Canada   

          day      time  predictions positive_probability negative_probability  
0  2020-08-11  08:34:02          0.0             0.406396             0.593604  
1  2020-08-14  04:12:05          0.0             0.332150             0.667850  
2  2020-08-17  06:40:59          0.0             0.419405             0.580595  
3  2020-08-16  09:25:31          0.0             0.224099             0.775901  
4  2020-07-28  03:02:35          0.0             0.400789             0.599211  

[5 rows x 25 columns]

In [24]:
# printing out first 50 positive tweets and the probability at how likely it is positive vs negative
data_country_random[['text','positive_probability','negative_probability']].loc[data_country_random['predictions'] == 1][:50]

text  positive_probability  \
12   A recent survey suggests that people are consi...              0.578747   
13   ICYMI With an expected rise in transfer studen...              0.624745   
14   karantacker narrates his 48hr ordeal which beg...              0.515527   
15   Are you a good communicator   \nteambuilding w...              0.638869   
17   Over 10 lakh people were tested for COVID19 fo...              0.532405   
19   Nature hinting at medicine for covid  Look it ...              0.641246   
22   In our recent blog we take a look at the futur...              0.570160   
23   we can still enjoy rooftops and beers  summer2...              0.638086   
31   The effect of COVID19 on DigitalDiplomacy watc...              0.645479   
50   Fuck your RNAVaccine to try and change my DNA ...              0.521533   
52   teninchscrews Nice playlist \n\nAlways enjoy y...              0.651234   
61            Pandemic UK COVID19 Covid_19 UK DAY_131               0.608078   
62   LosAngeles  guardaheartorg bhcplive and Intent...              0.514023   
65   Have to wonder Whats the SPF of my new Basebal...              0.517262   
67   Musical Artist Potentics \n\nLanguage African ...              0.562827   
69   Mark your calendars\n\n\nArab Cities amp COVID...              0.617504   
71   Haneen understood everything we tell her about...              0.531572   
72   With the Canadian economy gradually reopens du...              0.546618   
74   Thank you WSJ for telling us something we knew...              0.534823   
78    Dont forget to register for our ConnectingOnC...              0.527726   
81   COVID19 cost me my assistant coaching JUCO lax...              0.581579   
82   WARNING Health hazard borisvoteofnoconfidence ...              0.510532   
86   Such an important video For any hcps that need...              0.603191   
89   Dr Haqqani The impact of COVID19 on children  ...              0.550632   
92   Weekly US COVID19 deaths for each state as  of...              0.557267   
93   Rajamouli reveals that he tested mild positive...              0.624109   
102  Coming at 2pm tune in to the virtual COVID19 m...              0.632849   
108  Dr Jyoti Gulati aka my Mother goes live today ...              0.521251   
109  hrbartender Your Welcome Back to the Workplace...              0.581106   
110  Just another Commission done \nMy Design and t...              0.547967   
114  ALERT Bravo is open to bringing Dorinda Medley...              0.581740   
118  Cycling VueltaBurgos COVID19 \n\nCOVIDrecovere...              0.589776   
126  170000 dead Americans and a brother dyingTrump...              0.590527   
132  Let me assist you sell your property AbsaCyber...              0.525515   
139  COVID19 Testing Update  ICMRFIGHTSCOVID19 Indi...              0.545310   
141  RipCliffordRobinson he made the headband fashi...              0.558458   
145  Excellent piece from JamesTGallagher looking a...              0.571890   
149  COVID19 Updates\n\nIndia touches a mark of 3 C...              0.532946   
150  For my monthly DeccanChronicle column I wrote ...              0.516441   
154  The race is on to create a vaccine for covid19...              0.529910   
155  Lets pray  for everyone \nBe strong fightthevi...              0.594004   
158  Hope youve called that friend \nschoolsreopeni...              0.591608   
170                      An island NewZealand COVID19               0.677117   
173  HCL Launches Hackathon to Identify Technology ...              0.514176   
175  So excited about this Book Number one seller o...              0.529990   
176  StarSportsHub PhilstarNews mluisamorales_ How ...              0.570748   
182  Interesting article on the challenges of resta...              0.615662   
188                     See this DrSubhasree\n COVID19              0.533236   
191  Where are you at with the pace of change  Emer...              0.596795   
192  spar llwynhendy has on offer fresh fruit juic

In [25]:
# printing out first 50 negative tweets and the probability at how likely it is positive vs negative
data_country_random[['text','positive_probability','negative_probability']].loc[data_country_random['predictions'] == 0][:50]

text  positive_probability  \
0   Humans have unlimited needs but the planet has...              0.406396   
1   realDonaldTrump you will never run away from C...              0.332150   
2   Simply sitting never means doing nothing morni...              0.419405   
3   As millions of COVID19 funds flow into El Salv...              0.224099   
4   It probably wouldnt be possible to design a pa...              0.400789   
5   State Health Director Warns Coronavirus Is Wid...              0.391273   
6   CoronaUpdates for Virudhunagar \n\nCOVID19 cas...              0.347414   
7   WestBengal Trinamool Congress TMC MLA from Egr...              0.231383   
8   Demand for services like ours has only increas...              0.356197   
9   Todays COVID19 in  info and updates\n\nGOC web...              0.417757   
10  The parking which used to be full all the time...              0.351406   
11  Coronavirus Crisis CIOs Guide to COVID19  Coll...              0.475483   
16  So much speculation out there so Ill play The ...              0.317944   
18  We the students are the future of our state ou...              0.311663   
20        Ed Markey is correct COVID19 Massachusetts               0.365603   
21  In NYC there were 263 new COVID19 cases on Aug...              0.471186   
24  5080 GSM MATERIAL COVERALLS on sale  HealthZA ...              0.469583   
25  Does it feel right\ncoronavirus coronavirustes...              0.201915   
26  Pls like and subscribe to my channel   COVID19...              0.453352   
27  senatemajldr Bullshit HouseDemocrats passed CO...              0.361578   
28  Odisha reports biggest spike of COVID19 cases ...              0.339620   
29  As we certify COVID19 death cases it really br...              0.285417   
30  Misinformation on coronavirus is proving highl...              0.433230   
32  The graph is flattening slightly for India COV...              0.426727   
33  Voice check \n\nI am pretty positive I have CO...              0.470445   
34  The EU_EESC is awarding its CivilSolidarityPri...              0.321878   
35  The shortcummings of Johnsons Govt COVID19 cor...              0.318485   
36  In a major boost to Odishas fight against COVI...              0.270202   
37  VA announced its commitment to extend debt rel...              0.366589   
38  GidMK The flaw in your article is that you exp...              0.349103   
39  WHO When coughing or sneezing all members of a...              0.284129   
40  jleeannis Since I tweet alot on COVID19 I had ...              0.379354   
41  COVID19 infections are on a rise But you can d...              0.272851   
42  UAE airlines are seeing 4050 passenger capacit...              0.468043   
43  If you are operating a guest house apartment o...              0.484502   
44  Parabolic Projections New Daily cases COVID19 ...              0.383170   
45  Some personal news Im now picking up BayArea t...              0.397145   
46  In April we reported how the COVID19 pandemic ...              0.342653   
47  Singleday spike of 52050 positive cases amp 80...              0.376194   
48          COVID19 Deaths Nears 400Mark In Odisha \n              0.201284   
49  taylorh1986 FinancialTimes Actually the econom...              0.351337   
51  Study in Australia\nstudyabroad STUDY Australi...              0.447485   
53  Why are airlines pulling planes out of storage...              0.290572   
54  COVID19 Rex if you come home wet and muddy i w...              0.335645   
55  PLEASE TAKE THE SURVEY Lower tax collections b...              0.337332   
56  WhiteHouse realDonaldTrump We have the worst r...              0.224823   
57  nicolasturgeon has really been caught out with...              0.433128   
58  The Rmountaineer remains optimistic despite lo...              0.355829   
59  riddler_smitb Reckon it will be something with...              0.447056   
60  12 new COVID19 cases detected in Kandhamal inc...              0.388212   

    negative_probab

In [26]:
data_country_random.to_csv("covid_predictions_with_proba.csv")